apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: stable
apiServerCertSANs:
- "192.168.0.100"
controlPlaneEndpoint: "192.168.0.100:3016"
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://192.168.0.101:2379"
      advertise-client-urls: "https://192.168.0.101:2379"
      listen-peer-urls: "https://192.168.0.101:2380"
      initial-advertise-peer-urls: "https://192.168.0.101:2380"
      initial-cluster: "master-base=https://192.168.0.101:2380"
    serverCertSANs:
      - master-base
      - 192.168.0.101
    peerCertSANs:
      - master-base
      - CP0_IP
networking:
    # This CIDR is a Calico default. Substitute or remove for your CNI provider.
    podSubnet: "192.168.0.0/16"
