apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: stable
nodeName: "masterbase"
etcd:
  endpoints:
  - "http://192.168.0.103:2379"
  - "http://192.168.0.104:2379"
apiServerExtraArgs:
  apiserver-count: "2"
networking:
  podSubnet: "10.244.0.0/16"
apiServerCertSANs:
- "masterbase"
- "masterslave"
- "192.168.0.103"
- "192.168.0.104"
- "127.0.0.1"
