apiVersion: v1
kind: Service
metadata:
  name: test1
  labels:
    app: test1
spec:
  ports:
  - port: 80
    targetPort: 6060
    protocol: TCP
  type: NodePort
  selector:
    app: test1
  externalIPs:
    - 192.168.0.101
