apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: v1.10.3
networking:
  podSubnet: 10.244.0.0/16
apiServerCertSANs:
- masterv21
- masterv22
- 192.168.0.104
- 192.168.0.105
- 127.0.0.1
etcd:
  endpoints:
  - http://192.168.0.104:2379
  - http://192.168.0.105:2379
token: yf0t14.7ekahohaetbdphqg
tokenTTL: "0"
